# Generated by Django 4.2.2 on 2023-07-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuseravatar',
            name='icon',
            field=models.ImageField(default='to_do/avatars/default_icon.jpeg', upload_to='to_do/avatars', verbose_name='Аватарки'),
        ),
    ]
