# Generated by Django 4.2.2 on 2023-08-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0003_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='icon',
            field=models.ImageField(blank=True, upload_to='to_do/to_dos/%Y/%m/%d', verbose_name='Медиа'),
        ),
    ]
